server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/abol
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Am311865186

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop